proyectofinal/appblog/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.blog, name="blog"),
    path('categoria/<int:categoria_id>/', views.categoria, name="categoria"),
]

#creado manualmente

proyectofinal/appcarrito/urls.py
from django.urls import path
from . import views
app_name="carrito"

urlpatterns = [
    path('agregar/<int:producto_id>/', views.agregar_producto, name='agregar'),
    path('eliminar/<int:producto_id>/', views.eliminar_producto, name='eliminar'),
    path('restar/<int:producto_id>/', views.restar_producto, name='restar'),
    path('limpiar/', views.limpiar_carro, name='limpiar'),
]

proyectofinal/apptienda/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.tienda, name="tienda"),
    
]

proyectofinal/proyectofinal/urls.py
from os import stat
from django.contrib import admin
from django.urls import path, include
from django.conf import settings #importacion para urlpatterns+= para ver imagenes
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path("servicios/", include('appservicios.urls')),
    path("blog/", include('appblog.urls')),
    path("contacto/", include('appcontacto.urls')),
    path("tienda/", include('apptienda.urls')),
    path("carrito/", include('appcarrito.urls')),
    path("autenticacion/", include('appautenticacion.urls')),
    path("pedidos/", include('apppedidos.urls')),
    path("", include('proyectoapp.urls')),
    
]
urlpatterns+=static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT) #url para ver imagenes

proyectofinal/apptienda/models.py
from tkinter import CASCADE
from django.db import models

class categoriaProducto(models.Model):
    categoria=models.CharField(max_length=50)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateField(auto_now_add=True)

    class Meta():
        verbose_name="categoriaProducto"
        verbose_name_plural="categoriasProducto"
    def __str__(self):
        return self.categoria

class Producto(models.Model):
    nombre=models.CharField(max_length=25)
    categoria=models.ForeignKey(categoriaProducto, on_delete=models.CASCADE)
    imagen=models.ImageField(null=True, blank=True)
    precio=models.FloatField()
    disponibilidad=models.BooleanField()
    stock=models.PositiveIntegerField()
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now_add=True)
    


    class Meta():
        verbose_name="Producto"
        verbose_name_plural="Productos"
    def __str__(self):
        return self.nombre



# Create your models here.

proyectofinal/apptienda/views.py
from django.shortcuts import render
from .models import Producto



def tienda(request):
     lista=Producto.objects.all()
     return render(request, 'tienda.html', {"productos":lista})







# Create your views here.

proyectofinal/apptienda/templates/tienda.html
{% extends "base.html" %}
{% load static %}
{%block content%}
<div class="container">
  <div style="float:right; margin-left: 50px; size: 50%; margin-top:10px;" >
    {%if user.is_authenticated %}
      {% include "widget.html" %}
    {%endif %}
  </div>
  <div class="row" >
{%for i in productos %}
      <div class="col-md-4" >
        <div class="card" style="margin:10px;">
        <img class="card-img-top" src="{{i.imagen.url}}" style="height: 180px;">
      <div class="card-body" style="text-align: center;" >
          <h7 class="card-title">{{i.nombre}}</h7>
          <p class="card-test">$ {{i.precio}}</p>
        </div>
          <div class="card-footer text-center" style="height:70px;" >
            {%if user.is_authenticated %}
              <a href="{% url 'carrito:agregar' i.id%}" class="btn btn-success" style="width:100px;;">Agregar</a>
            {%else%}
            <a href="{% url 'login' %}" class="btn btn-success" style="width:100px;;">Agregar</a>

            {%endif %}

         </div>
      </div>
        
    </div>

{%endfor%}
    </div>
  </div>


{%endblock%}

proyectofinal/apptienda/templates/widget.html
<table class="table table-bordered" style="color:aquamarine;">
    <thead>
        <tr>
            <th colspan="3" class="text-center">

                Compras


            </th>






        </tr>

        <tr>
            <th>Producto: </th>
            <th>Cantidad: </th>
            <th>Total: </th>


        </tr>




    </thead>
    <tbody>
        {%if request.session.carrito.items %}
            {%for key, value in request.session.carrito.items %}
                <tr class="text-center">
                    <td>
                        {{value.nombre}}
                    </td>
                    <td>
                        {{value.cantidad}}
                    </td>
                    <td>
                        <a href="{% url 'carrito:agregar' value.producto_id %}" class="btn btn-sm btn-success" > + </a>
                        <a href="{% url 'carrito:restar' value.producto_id %}" class="btn btn-sm btn-success" > - </a>
                        <br>
                        $ {{value.precio}}
                    </td>

                </tr>

            {% endfor %}
        {% else %}
            <tr>
                <td colspan="3">
                    <div class="alert alert-danger text-center"> Sin Productos </div>
                </td>

            </tr>
        {% endif %}
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3">
                Total:$ {{importe_total}}

            </td>
        </tr>
        {% if request.session.carrito.items %}
        <tr>
            <td colspan="3" style="text-align:center ;">

                <a href="#" class="btn btn-sm btn-success"> Comprar</a>
            </td>
        </tr>
        {%endif%}
    </tfoot>


</table>